### ISSUE TITLE
Connection is not recovered

### ISSUE THREAD

**Issue by frederikbosch** [logstash-plugins/logstash-integration-rabbitmq#43] opened 2021-03-19 13:09 UTC
After a connection reset and close of the RabbitMQ connection, the connection is not recovered. The last message below is the last thing that is reported in the stdout until now, no reports in stderr.

```
E, [2021-03-13T07:22:24.998952 #1] ERROR -- #<MarchHare::Session:2046 mailerq-logstash@localhost:5672, vhost=mailerq>: An unexpected connection driver error occured
E, [2021-03-13T07:22:24.998959 #1] ERROR -- #<MarchHare::Session:2048 mailerq-logstash@localhost:5672, vhost=mailerq>: An unexpected connection driver error occured
E, [2021-03-13T07:22:24.998952 #1] ERROR -- #<MarchHare::Session:2050 mailerq-logstash@localhost:5672, vhost=mailerq>: An unexpected connection driver error occured
E, [2021-03-13T07:22:24.998953 #1] ERROR -- #<MarchHare::Session:2052 mailerq-logstash@localhost:5672, vhost=mailerq>: An unexpected connection driver error occured
E, [2021-03-13T07:22:25.002854 #1] ERROR -- #<MarchHare::Session:2048 mailerq-logstash@localhost:5672, vhost=mailerq>: Connection reset (Java::JavaNet::SocketException)
java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:293)
com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91)
com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:184)
com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:598)
java.base/java.lang.Thread.run(Thread.java:834)
E, [2021-03-13T07:22:25.002896 #1] ERROR -- #<MarchHare::Session:2046 mailerq-logstash@localhost:5672, vhost=mailerq>: Connection reset (Java::JavaNet::SocketException)
java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:293)
com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91)
com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:184)
com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:598)
java.base/java.lang.Thread.run(Thread.java:834)
E, [2021-03-13T07:22:25.002925 #1] ERROR -- #<MarchHare::Session:2050 mailerq-logstash@localhost:5672, vhost=mailerq>: Connection reset (Java::JavaNet::SocketException)
java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:293)
com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91)
com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:184)
com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:598)
java.base/java.lang.Thread.run(Thread.java:834)
E, [2021-03-13T07:22:25.002876 #1] ERROR -- #<MarchHare::Session:2052 mailerq-logstash@localhost:5672, vhost=mailerq>: Connection reset (Java::JavaNet::SocketException)
java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:293)
com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91)
com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:184)
com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:598)
java.base/java.lang.Thread.run(Thread.java:834)
E, [2021-03-13T07:22:30.158860 #1] ERROR -- #<MarchHare::Session:2052 mailerq-logstash@localhost:5672, vhost=mailerq>: Caught exception when recovering queue success
E, [2021-03-13T07:22:30.159491 #1] ERROR -- #<MarchHare::Session:2052 mailerq-logstash@localhost:5672, vhost=mailerq>: NOT_FOUND - home node 'rabbit@server03.rabbitmq.service.consul' of durable queue 'success' in vhost 'mailerq' is down or inaccessible (MarchHare::NotFound)
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:996:in `converting_rjc_exceptions_to_ruby'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:509:in `queue_declare'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/queue.rb:238:in `declare!'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/queue.rb:252:in `recover_from_network_failure'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:272:in `block in recover_queues'
org/jruby/RubyArray.java:1814:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:269:in `recover_queues'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:208:in `automatically_recover'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/session.rb:348:in `block in automatically_recover'
org/jruby/RubyArray.java:1814:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/session.rb:346:in `automatically_recover'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/session.rb:300:in `block in add_automatic_recovery_hook'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/shutdown_listener.rb:12:in `shutdown_completed'
E, [2021-03-13T07:22:30.162298 #1] ERROR -- #<MarchHare::Session:2050 mailerq-logstash@localhost:5672, vhost=mailerq>: Caught exception when recovering queue failure
E, [2021-03-13T07:22:30.162720 #1] ERROR -- #<MarchHare::Session:2050 mailerq-logstash@localhost:5672, vhost=mailerq>: NOT_FOUND - home node 'rabbit@server03.rabbitmq.service.consul' of durable queue 'failure' in vhost 'mailerq' is down or inaccessible (MarchHare::NotFound)
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:996:in `converting_rjc_exceptions_to_ruby'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:509:in `queue_declare'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/queue.rb:238:in `declare!'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/queue.rb:252:in `recover_from_network_failure'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:272:in `block in recover_queues'
org/jruby/RubyArray.java:1814:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:269:in `recover_queues'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:208:in `automatically_recover'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/session.rb:348:in `block in automatically_recover'
org/jruby/RubyArray.java:1814:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/session.rb:346:in `automatically_recover'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/session.rb:300:in `block in add_automatic_recovery_hook'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/shutdown_listener.rb:12:in `shutdown_completed'
E, [2021-03-13T07:22:30.163722 #1] ERROR -- #<MarchHare::Session:2048 mailerq-logstash@localhost:5672, vhost=mailerq>: Caught exception when recovering queue retry
E, [2021-03-13T07:22:30.164080 #1] ERROR -- #<MarchHare::Session:2048 mailerq-logstash@localhost:5672, vhost=mailerq>: NOT_FOUND - home node 'rabbit@server03.rabbitmq.service.consul' of durable queue 'retry' in vhost 'mailerq' is down or inaccessible (MarchHare::NotFound)
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:996:in `converting_rjc_exceptions_to_ruby'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:509:in `queue_declare'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/queue.rb:238:in `declare!'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/queue.rb:252:in `recover_from_network_failure'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:272:in `block in recover_queues'
org/jruby/RubyArray.java:1814:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:269:in `recover_queues'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:208:in `automatically_recover'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/session.rb:348:in `block in automatically_recover'
org/jruby/RubyArray.java:1814:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/session.rb:346:in `automatically_recover'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/session.rb:300:in `block in add_automatic_recovery_hook'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/shutdown_listener.rb:12:in `shutdown_completed'
E, [2021-03-13T07:22:30.196345 #1] ERROR -- #<MarchHare::Session:2052 mailerq-logstash@localhost:5672, vhost=mailerq>: Caught exception when recovering consumer amq.ctag-kZudDDsqBlqTtlsM9yvUlA
E, [2021-03-13T07:22:30.196345 #1] ERROR -- #<MarchHare::Session:2050 mailerq-logstash@localhost:5672, vhost=mailerq>: Caught exception when recovering consumer amq.ctag-qAkYqYvKMO-VmsRI671nmA
E, [2021-03-13T07:22:30.197071 #1] ERROR -- #<MarchHare::Session:2050 mailerq-logstash@localhost:5672, vhost=mailerq>: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - home node 'rabbit@server03.rabbitmq.service.consul' of durable queue 'failure' in vhost 'mailerq' is down or inaccessible, class-id=50, method-id=10) (MarchHare::ChannelAlreadyClosed)
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:996:in `converting_rjc_exceptions_to_ruby'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:629:in `basic_consume'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/consumers/base.rb:87:in `recover_from_network_failure'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:287:in `block in recover_consumers'
org/jruby/RubyArray.java:1814:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:283:in `recover_consumers'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:209:in `automatically_recover'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/session.rb:348:in `block in automatically_recover'
org/jruby/RubyArray.java:1814:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/session.rb:346:in `automatically_recover'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/session.rb:300:in `block in add_automatic_recovery_hook'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/shutdown_listener.rb:12:in `shutdown_completed'
E, [2021-03-13T07:22:30.197010 #1] ERROR -- #<MarchHare::Session:2052 mailerq-logstash@localhost:5672, vhost=mailerq>: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - home node 'rabbit@server03.rabbitmq.service.consul' of durable queue 'success' in vhost 'mailerq' is down or inaccessible, class-id=50, method-id=10) (MarchHare::ChannelAlreadyClosed)
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:996:in `converting_rjc_exceptions_to_ruby'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:629:in `basic_consume'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/consumers/base.rb:87:in `recover_from_network_failure'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:287:in `block in recover_consumers'
org/jruby/RubyArray.java:1814:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:283:in `recover_consumers'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:209:in `automatically_recover'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/session.rb:348:in `block in automatically_recover'
org/jruby/RubyArray.java:1814:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/session.rb:346:in `automatically_recover'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/session.rb:300:in `block in add_automatic_recovery_hook'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/shutdown_listener.rb:12:in `shutdown_completed'
E, [2021-03-13T07:22:30.197524 #1] ERROR -- #<MarchHare::Session:2048 mailerq-logstash@localhost:5672, vhost=mailerq>: Caught exception when recovering consumer amq.ctag-ExTe9XX05ukOvJzklyHmAQ
E, [2021-03-13T07:22:30.198195 #1] ERROR -- #<MarchHare::Session:2048 mailerq-logstash@localhost:5672, vhost=mailerq>: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - home node 'rabbit@server03.rabbitmq.service.consul' of durable queue 'retry' in vhost 'mailerq' is down or inaccessible, class-id=50, method-id=10) (MarchHare::ChannelAlreadyClosed)
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:996:in `converting_rjc_exceptions_to_ruby'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:629:in `basic_consume'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/consumers/base.rb:87:in `recover_from_network_failure'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:287:in `block in recover_consumers'
org/jruby/RubyArray.java:1814:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:283:in `recover_consumers'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/channel.rb:209:in `automatically_recover'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/session.rb:348:in `block in automatically_recover'
org/jruby/RubyArray.java:1814:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/session.rb:346:in `automatically_recover'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/session.rb:300:in `block in add_automatic_recovery_hook'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.1-java/lib/march_hare/shutdown_listener.rb:12:in `shutdown_completed'
[2021-03-13T07:22:30,205][WARN ][logstash.inputs.rabbitmq ][main] RabbitMQ connection was closed! {:url=>"amqp://mailerq-logstash:XXXXXX@localhost:5672mailerq", :automatic_recovery=>true, :cause=>com.rabbitmq.client.ShutdownSignalException: connection error}
[2021-03-13T07:22:30,205][WARN ][logstash.inputs.rabbitmq ][main] RabbitMQ connection was closed! {:url=>"amqp://mailerq-logstash:XXXXXX@localhost:5672mailerq", :automatic_recovery=>true, :cause=>com.rabbitmq.client.ShutdownSignalException: connection error}
[2021-03-13T07:22:30,205][WARN ][logstash.inputs.rabbitmq ][main] RabbitMQ connection was closed! {:url=>"amqp://mailerq-logstash:XXXXXX@localhost:5672mailerq", :automatic_recovery=>true, :cause=>com.rabbitmq.client.ShutdownSignalException: connection error}
[2021-03-13T07:22:30,205][WARN ][logstash.inputs.rabbitmq ][main] RabbitMQ connection was closed! {:url=>"amqp://mailerq-logstash:XXXXXX@localhost:5672mailerq", :automatic_recovery=>true, :cause=>com.rabbitmq.client.ShutdownSignalException: connection error}
```

**Comment by andsel** [comment] 2021-05-12 08:12
Some simple steps to reproduce it running a local dockerized RabbitMQ, a simple Logstash pipeline and RabbitMQ sender script:
- start Rabbit: `docker run -p 5672:5672 -p 15672:15672 --hostname my-rabbit rabbitmq:3-management` then go to `http://localhost:15672/#/queues` with a browser to monitor it (credentials guest:guest)
- install Rabbit integration on LS `logstash-7.11.2/bin/logstash-plugin install logstash-integration-rabbitmq`
- install the March Hare gem on local machine, `gem install march_hare`
- start the [script to push data](https://gist.github.com/andsel/1d3a734337d29023680ac9a5cd349d18)  `ruby sender.rb`
- run Logstash with the puller pipeline `logstash-7.11.2/bin/logstash -f pipeline.conf`
- kill and restart the docker image


```
input {
  rabbitmq {
    codec => plain # codec (optional), default: "plain"
    exchange => "sysmsg" # string (optional)
    host => "localhost" # string (required)
    vhost => "/"
    user => 'guest'
    password => 'guest'
    queue => "iot_queue"

  }
}

output {
  stdout {
    codec => rubydebug
  }    
}

```

**Comment by andsel** [comment] 2022-02-09 12:05
I'm not able to reproduce the error. With Logstash version `7.8.0` I got a similar stdout log:
```
E, [2022-02-09T12:51:39.075322 #3308500] ERROR -- #<MarchHare::Session:2048 guest@localhost:5672, vhost=/>: An unexpected connection driver error occured
E, [2022-02-09T12:51:39.084079 #3308500] ERROR -- #<MarchHare::Session:2048 guest@localhost:5672, vhost=/>: Connection reset (Java::JavaNet::SocketException)
java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:293)
com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91)
com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:184)
com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:598)
java.base/java.lang.Thread.run(Thread.java:829)
[2022-02-09T12:51:44,176][WARN ][logstash.inputs.rabbitmq ][main][e78725282315e2c8afc972c397af7c336f135c4040a5c8ef1e74617e63d75b55] RabbitMQ connection was closed! {:url=>"amqp://guest:XXXXXX@localhost:5672/", :automatic_recovery=>true, :cause=>com.rabbitmq.client.ShutdownSignalException: connection error}
{
    "@timestamp" => 2022-02-09T11:51:44.167Z,
       "message" => "27C",
      "@version" => "1"
}

```

but after a restart of the docker container with `docker restart rabbit_dev` and the restart of the sender script, the flow of event continued without problem.

Please @frederikbosch could you try again with a more updated version of the plugin / Logstash, because some improvements on logging side was released with version `7.3.0` of the plugin.
How to reproduce it?

I leave a quick overview of the versions, `4.1.1` of march-hare was used in Logstash `7.8`

| Logstash   |      rabbit plugin      |  march-hare |
|----------|:-------------:|------:|
| `7.17.0` |  `7.3.0` | [`4.4.0`](https://github.com/elastic/logstash/blob/v7.17.0/Gemfile.jruby-2.5.lock.release#L669) |
| `7.11.2` |    `7.1.1`   |   [`4.3.0`](https://github.com/elastic/logstash/blob/v7.11.2/Gemfile.jruby-2.5.lock.release#L547) |
| `7.9.0` |    `7.1.0`   |   [`4.2.0`](https://github.com/elastic/logstash/blob/v7.9.0/Gemfile.jruby-2.5.lock.release#L539) |
| `7.8.0` |    `7.0.3`   |   [`4.1.1`](https://github.com/elastic/logstash/blob/v7.8.0/Gemfile.jruby-2.5.lock.release#L535) |

**Comment by frederikbosch** [comment] 2022-02-09 13:15
In production I am using the Official Docker 7.16.1 and just disabled my workaround for this problem. I will let you know my results soon.

**Closed** 2022-02-09 13:17 UTC
Labels: bug, status:needs-triage, int-shortlist

**Comment by frederikbosch** [comment] 2022-02-09 13:18
I just noticed that another container - also running 7.16.1 - already had the workaround removed, and had no crash for 2 months. I will reopen if it happens again.
